homeassistant:
  name: RomaHome
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/Helsinki
  customize: !include customize.yaml

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

map:

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret aqara_key

mqtt:
  broker: !secret mqtt_server
  port: !secret mqtt_port
  client_id: home_assistant
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password

device_tracker:
  - platform: nmap_tracker
    hosts:
     - 192.168.0.3
     - 192.168.0.6
    home_interval: 10
    scan_options: " --privileged -sP --host-timeout 10s --max-rate 100 "

zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 100
    icon: mdi:account-multiple

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chatID_group

notify:
  - name: telegram
    platform: telegram
    api_key: !secret telegram_api
    chat_id: !secret telegram_chatID_group

group: !include groups.yaml
automation: !include_dir_merge_list automation
alarm_control_panel: !include alarm.yaml
script: !include_dir_merge_named scripts
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_number: !include input_number.yaml
scene: !include scenes.yaml
