default_view:
    view: yes
    icon: mdi:home
    entities:
        - group.heating
        - group.alarm
        - group.doors
        - group.livingroom
        - group.bedroom
        - device_tracker.roniphone_roni
        - device_tracker.marlephone_marle
        - media_player.romacast_makuuhuone

automation:
    name: Automaatio
    view: yes
    icon: mdi:robot
    entities:
        - group.automation_settings
        
heating:
    name: Ilmalämpöpumppu
    entities:
        - input_number.target_temperature
    
livingroom:
    name: Olohuone
    entities:
        - sensor.temperature_158d0002375005
        - sensor.humidity_158d0002375005
        #- light.olohuone_jalkalamppu
        
bedroom:
    name: Makuuhuone
    entities:
        - light.makuuhuone_jalkalamppu
        - scene.bedroom_full
        - scene.bedroom_comfy
        - scene.bedroom_media

automation_settings:
    name: Automaatioasetukset
    entities:
        - input_boolean.light_automation
        - input_boolean.heat_pump_automation
        
doors:
    name: Ovet 
    entities:
        - binary_sensor.door_window_sensor_158d000205b37c

family:
    name: Perhe
    entities:
        - device_tracker.roniphone_roni
        - device_tracker.marlephone_marle
        
alarm:
    name: Varashälytin
    icon: mdi:shield
    entities:
        - alarm_control_panel.ha_alarm