default_view:
    view: yes
    icon: mdi:home
    entities:
        - group.livingroom
        - group.bedroom
        - media_player.romacast_makuuhuone

automation:
    name: Automaatio
    view: yes
    icon: mdi:robot
    entities:
        - group.automation_settings
    
livingroom:
    name: Olohuone
    entities:
        - light.olohuone_jalkalamppu
        
bedroom:
    name: Makuuhuone
    entities:
        - light.makuuhuone_jalkalamppu
        - scene.bedroom_full
        - scene.bedroom_comfy
        - scene.bedroom_media

automation_settings:
    name: Automaatioasetukset
    entities:
        - input_boolean.light_automation
    